/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd.Operador;

import BackEnd.Envios;
import FrontEnd.PantallaGerente;
import BackEnd.Sedes;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import BackEnd.Clientes;

/**
 *
 * @author alejandro
 */
public class RegistrarClientes extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarSede
     */
    
    int valorSuma = 0;
    int valorPaqueteSuma = 0;
    int valorImpuestoSuma = 0;
    int valorSeguroSuma = 0;
    int conteoPaquetes = 0;
    String sedeAsignadaAlCliente = "";
    boolean seAsignoSede = false;
    
    public RegistrarClientes() {
        initComponents();
        lRegistrarCliente.setEnabled(false);
    }
    
public boolean validador(){
        boolean validacion = true;
        String respuesta = "Por favor verifique:";
        
        if( jtfNombre.getText().length()<1 ){
            respuesta = respuesta + "\n   - Debe ingresar un nombre";
            validacion = false;
        }
        if( jtfCedula.getText().length()<1 || (jtfCedula.getText().length()>0 && !(jtfCedula.getText().matches("[+-]?\\d*(\\.\\d+)?")) )){
            respuesta = respuesta + "\n   - Cédula ingresada, deben ser solo números";
            jtfCedula.setText("");
            validacion = false;
        }
        if( jtfDireccion.getText().length()<1 ){
            respuesta = respuesta + "\n   - Debe ingresar una dirección";
            validacion = false;
        }
        if( jtfComuna.getText().length()<1 || (jtfComuna.getText().length()>0 && !(jtfComuna.getText().matches("[+]?\\d*(\\.\\d+)?")) )){
            respuesta = respuesta + "\n   - Comuna ingresado, deben ser solo números positivos";
            jtfComuna.setText("");
            validacion = false;
        }
        
        if( !validacion )
            JOptionPane.showMessageDialog(null, respuesta);
        
        return validacion;
    }

public String hallarSedeCercana(int comunaCliente){
    Sedes sede = new Sedes();
    String sedeCercana = "";
    
    String[] listaDeSedes = sede.getIdYComunaSedes().split(":");
    int distanciaSedeACliente = 10000000;
    
    for(int i=0; i< listaDeSedes.length ;i++){
        if(i%2 == 0){
            if( Math.abs( Integer.parseInt(listaDeSedes[i]) - comunaCliente) <  distanciaSedeACliente){
                distanciaSedeACliente = Math.abs(Integer.parseInt( listaDeSedes[i]) - comunaCliente);
                sedeCercana = listaDeSedes[i+1];
            }
        }
    }
    return sedeCercana;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEnvio = new javax.swing.JPanel();
        lRegistrarCliente = new javax.swing.JLabel();
        lCancelar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfDireccion = new javax.swing.JTextField();
        jtfCedula = new javax.swing.JTextField();
        jtfComuna = new javax.swing.JTextField();
        lSedeAsignada = new javax.swing.JLabel();
        lAsignarSede = new javax.swing.JLabel();

        jpEnvio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));

        lRegistrarCliente.setBackground(new java.awt.Color(0, 153, 102));
        lRegistrarCliente.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        lRegistrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lRegistrarCliente.setText("Registrar");
        lRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lRegistrarCliente.setEnabled(false);
        lRegistrarCliente.setOpaque(true);
        lRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lRegistrarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lRegistrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lRegistrarClienteMouseExited(evt);
            }
        });

        lCancelar.setBackground(new java.awt.Color(0, 153, 102));
        lCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCancelar.setText("Cancelar");
        lCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lCancelar.setOpaque(true);
        lCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lCancelarMouseExited(evt);
            }
        });

        jLabel13.setText("Nombre");

        jLabel14.setText("Direccion");

        jLabel16.setText("Cedula");

        jLabel18.setText("Comuna");

        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDireccion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComuna)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lSedeAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jtfComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lSedeAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        lAsignarSede.setBackground(new java.awt.Color(0, 153, 102));
        lAsignarSede.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lAsignarSede.setForeground(new java.awt.Color(255, 255, 255));
        lAsignarSede.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAsignarSede.setText("Asignar sede");
        lAsignarSede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lAsignarSede.setOpaque(true);
        lAsignarSede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAsignarSedeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lAsignarSedeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lAsignarSedeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpEnvioLayout = new javax.swing.GroupLayout(jpEnvio);
        jpEnvio.setLayout(jpEnvioLayout);
        jpEnvioLayout.setHorizontalGroup(
            jpEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnvioLayout.createSequentialGroup()
                .addGroup(jpEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnvioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpEnvioLayout.createSequentialGroup()
                        .addGroup(jpEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnvioLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(lCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpEnvioLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(lRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(lAsignarSede, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpEnvioLayout.setVerticalGroup(
            jpEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnvioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAsignarSede, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCancelarMouseClicked
        // TODO add your handling code here:
        //new PantallaGeneralGerente().setVisible(true);
        //this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_lCancelarMouseClicked

    private void lCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCancelarMouseEntered
        // TODO add your handling code here:
        lCancelar.setForeground(Color.red);
    }//GEN-LAST:event_lCancelarMouseEntered

    private void lCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCancelarMouseExited
        // TODO add your handling code here:
        lCancelar.setForeground(Color.white);
    }//GEN-LAST:event_lCancelarMouseExited

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void lRegistrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrarClienteMouseExited
        // TODO add your handling code here:
        lRegistrarCliente.setForeground(Color.WHITE);
    }//GEN-LAST:event_lRegistrarClienteMouseExited

    private void lRegistrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrarClienteMouseEntered
        // TODO add your handling code here:
        lRegistrarCliente.setForeground(Color.red);
    }//GEN-LAST:event_lRegistrarClienteMouseEntered

    private void lRegistrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrarClienteMouseClicked
        // AQUI SE REGISTRA EL USUARIO
        Clientes cliente = new Clientes();        
        
        try {
            if ( seAsignoSede ){
                if ( validador() ){
                    if( !( cliente.cedulaExiste( jtfCedula.getText() ) ) ){
                        int comuna = Integer.parseInt(jtfComuna.getText());
                        cliente.registrarClienteNuevo(jtfCedula.getText(), jtfNombre.getText(), jtfDireccion.getText(), comuna, sedeAsignadaAlCliente);
                        jtfCedula.setText("");
                        jtfNombre.setText("");
                        jtfDireccion.setText("");
                        jtfComuna.setText("");
                        lSedeAsignada.setText("");
                        JOptionPane.showMessageDialog(null, "Cliente registrado exitosamente", "Sistematizacion De Procesos - Flash", JOptionPane.INFORMATION_MESSAGE);
                        jtfComuna.setEnabled(true);
                        seAsignoSede = false;
                        lRegistrarCliente.setEnabled(false);
                    }
                    else
                        JOptionPane.showMessageDialog(null, "La cédula ya existe");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lRegistrarClienteMouseClicked

    private void lAsignarSedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAsignarSedeMouseClicked
        if( ( jtfComuna.getText().length()>0 && jtfComuna.getText().matches("[+-]?\\d*(\\.\\d+)?")) ){
            Sedes unaSede = new Sedes();
            try{
                int comunaCliente = Integer.parseInt(jtfComuna.getText());
                sedeAsignadaAlCliente = hallarSedeCercana(comunaCliente);

                lSedeAsignada.setText("Al cliente se le asigno la sede " + sedeAsignadaAlCliente);
                seAsignoSede = true;
                jtfComuna.setEnabled(false);
                lRegistrarCliente.setEnabled(true);
            } catch (NumberFormatException exc) {
                Logger.getLogger(RegistrarClientes.class.getName()).log(Level.SEVERE, null, exc);
                //JOptionPane.showMessageDialog(null, "Exc: " + exc);
            }            
            jtfComuna.setEnabled(false);
            lRegistrarCliente.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "La comuna ingresada no es válida");
        }
    }//GEN-LAST:event_lAsignarSedeMouseClicked

    private void lAsignarSedeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAsignarSedeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lAsignarSedeMouseEntered

    private void lAsignarSedeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAsignarSedeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lAsignarSedeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jpEnvio;
    javax.swing.JTextField jtfCedula;
    javax.swing.JTextField jtfComuna;
    javax.swing.JTextField jtfDireccion;
    javax.swing.JTextField jtfNombre;
    javax.swing.JLabel lAsignarSede;
    javax.swing.JLabel lCancelar;
    public javax.swing.JLabel lRegistrarCliente;
    private javax.swing.JLabel lSedeAsignada;
    // End of variables declaration//GEN-END:variables
}
