/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd.Secretaria;

import BackEnd.ConexionBD;
import FrontEnd.Administrativo.*;
import FrontEnd.PantallaGerente;
import BackEnd.Sedes;
import BackEnd.Usuarios;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alejandro
 */
public class ReporteValorPaquetes extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarSede
     */
    public ReporteValorPaquetes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_valorTRT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_valorTR = new javax.swing.JTextField();
        btnPtarjeta = new javax.swing.JLabel();
        btnPagosEfectivo = new javax.swing.JLabel();

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPORTE DEL VALOR DE LOS PAQUETES ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel2)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setText("Valor TOTAL de los paquetes REGISTRADOS pagados con tarjeta: ");

        jtxt_valorTRT.setEditable(false);
        jtxt_valorTRT.setEnabled(false);

        jLabel4.setText("Valor TOTAL de los paquetes REGISTRADOS pagados con efectivo");

        jtxt_valorTR.setEditable(false);
        jtxt_valorTR.setEnabled(false);

        btnPtarjeta.setBackground(new java.awt.Color(0, 153, 102));
        btnPtarjeta.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnPtarjeta.setForeground(new java.awt.Color(255, 255, 255));
        btnPtarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPtarjeta.setText("PAGOS CON TARJETA");
        btnPtarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPtarjeta.setOpaque(true);
        btnPtarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPtarjetaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPtarjetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPtarjetaMouseExited(evt);
            }
        });

        btnPagosEfectivo.setBackground(new java.awt.Color(0, 153, 102));
        btnPagosEfectivo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnPagosEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        btnPagosEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPagosEfectivo.setText("Usuarios por sede");
        btnPagosEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPagosEfectivo.setOpaque(true);
        btnPagosEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagosEfectivoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagosEfectivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagosEfectivoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jtxt_valorTRT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPtarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jtxt_valorTR, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnPagosEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_valorTRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPtarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_valorTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagosEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPtarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPtarjetaMouseClicked
        // TODO add your handling code here:
        Usuarios listaUsuarios = new Usuarios();
        try {

            DefaultTableModel modelo;
            ConexionBD con = new ConexionBD();
            String sql = "";
            java.sql.Connection conexion = con.getConexion();
            java.sql.Statement stmt = con.getStm();

            conexion = DriverManager.getConnection(con.getUrl(), con.getUser(), con.getPassword());
            sql = "SELECT SUM(valor_paquetes) FROM envios WHERE (metodo_pago = 'Tarjeta De Credito') OR (metodo_pago = 'Tarjeta Debito')";

            stmt = conexion.createStatement();

            ResultSet rstm = stmt.executeQuery(sql);

            while (rstm.next()) {
                jtxt_valorTRT.setText(String.valueOf(rstm.getInt("sum")));
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(ListarUsuariosTabulados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPtarjetaMouseClicked

    private void btnPtarjetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPtarjetaMouseEntered
        // TODO add your handling code here:
        btnPtarjeta.setForeground(Color.red);
    }//GEN-LAST:event_btnPtarjetaMouseEntered

    private void btnPtarjetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPtarjetaMouseExited
        // TODO add your handling code here:
        btnPtarjeta.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPtarjetaMouseExited

    private void btnPagosEfectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosEfectivoMouseClicked
        Usuarios listaUsuarios = new Usuarios();
        try {

            DefaultTableModel modelo;
            ConexionBD con = new ConexionBD();
            String sql = "";
            java.sql.Connection conexion = con.getConexion();
            java.sql.Statement stmt = con.getStm();

            conexion = DriverManager.getConnection(con.getUrl(), con.getUser(), con.getPassword());
            sql = "SELECT SUM(valor_paquetes) FROM envios\n"
                    + "WHERE metodo_pago = 'Efectivo'";

            stmt = conexion.createStatement();

            ResultSet rstm = stmt.executeQuery(sql);

            while (rstm.next()) {
                jtxt_valorTR.setText(String.valueOf(rstm.getInt("sum")));
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(ListarUsuariosTabulados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPagosEfectivoMouseClicked

    private void btnPagosEfectivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosEfectivoMouseEntered
        // TODO add your handling code here:
        //listarPorSede.setForeground(Color.red);
    }//GEN-LAST:event_btnPagosEfectivoMouseEntered

    private void btnPagosEfectivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosEfectivoMouseExited


    }//GEN-LAST:event_btnPagosEfectivoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel btnPagosEfectivo;
    javax.swing.JLabel btnPtarjeta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jtxt_valorTR;
    private javax.swing.JTextField jtxt_valorTRT;
    // End of variables declaration//GEN-END:variables
}
