/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd.Administrativo;

import BackEnd.ConexionBD;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import BackEnd.ConexionBD;
import BackEnd.Sedes;
import com.itextpdf.text.Document;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luisg
 */
public class ListarClientes extends javax.swing.JPanel {

    /**
     * Creates new form ListarClientes
     */
    public ListarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        listarClientesTotales = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbl_clientes = new javax.swing.JTable();

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));

        listarClientesTotales.setBackground(new java.awt.Color(0, 153, 102));
        listarClientesTotales.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        listarClientesTotales.setForeground(new java.awt.Color(255, 255, 255));
        listarClientesTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarClientesTotales.setText("Clientes totales");
        listarClientesTotales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listarClientesTotales.setOpaque(true);
        listarClientesTotales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarClientesTotalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listarClientesTotalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listarClientesTotalesMouseExited(evt);
            }
        });

        jTbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Direccion", "Id comuna", "Sede"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTbl_clientes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(listarClientesTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(listarClientesTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listarClientesTotalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarClientesTotalesMouseClicked
        // TODO add your handling code here:
        //Usuarios listaUsuarios = new Usuarios();
        jTbl_clientes.setModel(new DefaultTableModel());
        DefaultTableModel modelo;
        ConexionBD con = new ConexionBD();
        String sql = "";
        java.sql.Connection conexion = con.getConexion();
        java.sql.Statement stmt = con.getStm();

        try {
            conexion = DriverManager.getConnection(con.getUrl(), con.getUser(), con.getPassword());
        } catch (SQLException ex) {
            Logger.getLogger(ListarUsuariosTabulados.class.getName()).log(Level.SEVERE, null, ex);
        }

        String[] nmClm = {"Cedula", "Nombre", "Direccion", "Id Comuna", "Sede"};

        sql = "SELECT * FROM clientes";

        modelo = (DefaultTableModel) jTbl_clientes.getModel();

        modelo.setColumnIdentifiers(nmClm);

        jTbl_clientes.setModel(modelo);

        String[] registro = new String[5];

        try {
            stmt = conexion.createStatement();

            ResultSet rstm = stmt.executeQuery(sql);

            while (rstm.next()) {
                registro[0] = rstm.getString(1);
                registro[1] = rstm.getString(2);
                registro[2] = rstm.getString(3);
                registro[3] = rstm.getString(4);
                registro[4] = rstm.getString(5);

                modelo.addRow(registro);
            }
            jTbl_clientes.setVisible(true);

            conexion.close();

        } catch (SQLException ex) {
            Logger.getLogger(ListarUsuariosTabulados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listarClientesTotalesMouseClicked

    private void listarClientesTotalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarClientesTotalesMouseEntered
        // TODO add your handling code here:
        listarClientesTotales.setForeground(Color.red);
    }//GEN-LAST:event_listarClientesTotalesMouseEntered

    private void listarClientesTotalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarClientesTotalesMouseExited
        // TODO add your handling code here:
        listarClientesTotales.setForeground(Color.WHITE);
    }//GEN-LAST:event_listarClientesTotalesMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbl_clientes;
    javax.swing.JLabel listarClientesTotales;
    // End of variables declaration//GEN-END:variables
}
